export const Translations = {
  unknownComponent: 'Unknown component',
  deleteComponent: 'Remove component',
  copyPage: 'Copier le code de la page',
  copyComponent: 'Copy the component',
  searchComponent: 'Search a component',
  copySuccess: 'The code has been copied',
  copyInstructions: 'You can paste the component on another page (CTRL + V)',
  addComponent: 'Add a component',
  responsiveView: 'Responsive view',
  addItem: 'Add an item',
  deleteItem: 'Remove item',
  rollback: 'Restore',
  deleteItemConfirm: 'The component has been deleted',
  save: 'Save',
  close: 'Close',
  closeConfirm: 'Close the editor? Unsaved changes will be lost.',
  allBlocs: 'All blocks',
  noContent: `You have no content yet`,
  useTemplate: 'Use a template',
  poweredBy: 'Powered by',
  // Block categories
  categoryText: 'Text',
  categoryImage: 'Image',
  categoryVideo: 'Video',
  categoryMusic: 'Music',
  categoryButton: 'Button',
  // Block titles
  simpleTextTitle: 'Simple text',
  buttonTitle: 'Button',
  simpleImageTitle: 'Simple image',
  galleryImagesTitle: 'Image gallery',
  youtubeVideoTitle: 'YouTube video',
  youtubePlaylistTitle: 'YouTube playlist',
  dailymotionTitle: 'Dailymotion video',
  spotifyPlaylistTitle: 'Spotify playlist',
  spotifyTrackTitle: 'Spotify track',
  spotifyPodcastTitle: 'Spotify podcast',
  spotifyAlbumTitle: 'Spotify album',
  spotifyArtistTitle: 'Spotify artist',
  soundcloudTrackTitle: 'Soundcloud track',
  soundcloudPlaylistTitle: 'Soundcloud playlist',
  bandcampTitle: 'Bandcamp',
  tidalPlaylistTitle: 'Tidal playlist',
  tidalTrackTitle: 'Tidal track',
  tidalAlbumTitle: 'Tidal album',
  // Block field labels
  simpleTextContent: 'Content',
  buttonUrl: 'Button URL',
  buttonLabel: 'Button text',
  imageUrl: 'Image URL',
  imageAlt: 'Alt text (SEO)',
  imagesLabel: 'Images',
  imageAddLabel: 'Add an image',
  videoUrl: 'Video URL',
  playlistUrl: 'Playlist URL',
  trackUrl: 'Track URL',
  albumUrl: 'Album URL',
  artistUrl: 'Artist URL',
  podcastUrl: 'Podcast URL',
  soundcloudId: 'Track ID',
  soundcloudHelp: 'The ID is in the Embed section',
  bandcampId: 'Bandcamp ID',
  bandcampHelp: 'The ID is in the Embed section',
  bandcampType: 'Type',
  bandcampTypeTrack: 'Track',
  bandcampTypeAlbum: 'Album',
  playerSize: 'Size',
  playerSizeNormal: 'Normal',
  playerSizeCompact: 'Compact',
  playerSizeSmall: 'Small',
  playerSizeLargeBig: 'Standard (large artwork)',
  playerSizeLargeSmall: 'Standard (small artwork)',
  playerTheme: 'Theme',
  playerThemeDark: 'Dark',
  playerThemeColored: 'Colored',
  playerThemeLight: 'Light',
  playerStyle: 'Style',
  playerStyleVisual: 'Visual',
  playerStyleClassic: 'Classic',
}
