export const Translations = {
  copyPage: 'Copier le code de la page',
  deleteComponent: 'Supprimer le bloc',
  copyComponent: 'Copier le  bloc',
  searchComponent: 'Rechercher un bloc',
  copySuccess: 'Le code a bién été copié',
  copyInstructions: 'vous pouvez le coller sur une autre page (CTRL + V)',
  addComponent: 'Ajouter un bloc',
  responsiveView: 'Vue responsive',
  addItem: 'Ajouter un élément',
  deleteItem: "Supprimer l'élément",
  rollback: 'Rétablir',
  deleteItemConfirm: 'Le bloc a bien été supprimé',
  unknownComponent: 'Bloc inconnu',
  save: 'Sauvegarder',
  close: 'Fermer',
  poweredBy: 'Propulsé par',
  noContent: `Vous n'avez pas encore de contenu`,
  useTemplate: 'Utilisez un template',
  // Catégories de blocs
  categoryText: 'Texte',
  categoryImage: 'Image',
  categoryVideo: 'Vidéo',
  categoryMusic: 'Musique',
  categoryButton: 'Bouton',
  // Titres des blocs
  simpleTextTitle: 'Texte simple',
  buttonTitle: 'Bouton',
  simpleImageTitle: 'Image simple',
  galleryImagesTitle: "Galerie d'images",
  youtubeVideoTitle: 'Vidéo YouTube',
  youtubePlaylistTitle: 'Playlist YouTube',
  dailymotionTitle: 'Vidéo Dailymotion',
  spotifyPlaylistTitle: 'Playlist Spotify',
  spotifyTrackTitle: 'Morceau Spotify',
  spotifyPodcastTitle: 'Podcast Spotify',
  spotifyAlbumTitle: 'Album Spotify',
  spotifyArtistTitle: 'Artiste Spotify',
  soundcloudTrackTitle: 'Morceau Soundcloud',
  soundcloudPlaylistTitle: 'Playlist Soundcloud',
  bandcampTitle: 'Bandcamp',
  tidalPlaylistTitle: 'Playlist Tidal',
  tidalTrackTitle: 'Morceau Tidal',
  tidalAlbumTitle: 'Album Tidal',
  // Labels des champs
  simpleTextContent: 'Contenu',
  buttonUrl: 'URL du bouton',
  buttonLabel: 'Texte du bouton',
  imageUrl: "URL de l'image",
  imageAlt: 'Texte alternatif (SEO)',
  imagesLabel: 'Images',
  imageAddLabel: 'Ajouter une image',
  videoUrl: 'URL de la vidéo',
  playlistUrl: 'URL de la playlist',
  trackUrl: 'URL du morceau',
  albumUrl: "URL de l'album",
  artistUrl: "URL de l'artiste",
  podcastUrl: 'URL du podcast',
  soundcloudId: 'Identifiant du morceau',
  soundcloudHelp: "L'identifiant se trouve dans la partie Intégration",
  bandcampId: 'Identifiant',
  bandcampHelp: "L'identifiant se trouve dans la partie Intégration",
  bandcampType: 'Type',
  bandcampTypeTrack: 'Morceau',
  bandcampTypeAlbum: 'Album',
  playerSize: 'Taille',
  playerSizeNormal: 'Normale',
  playerSizeCompact: 'Compacte',
  playerSizeSmall: 'Mince',
  playerSizeLargeBig: 'Standard (image grande)',
  playerSizeLargeSmall: 'Standard (image petite)',
  playerTheme: 'Thème',
  playerThemeDark: 'Noir',
  playerThemeColored: 'Coloré',
  playerThemeLight: 'Blanc',
  playerStyle: 'Style',
  playerStyleVisual: 'Visuel',
  playerStyleClassic: 'Classique',
}
