name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Install Node dependencies
        run: npm install
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Build the library
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Run E2E tests
        run: npm run test:e2e
